#!/bin/sh
#
# @name Gazebo q940_ti_gripper3
#
# @type Quadrotor
#

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=laboratory_landingbox}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=q940_ti_gripper3}
PX4_GZ_MODEL_POSE=${PX4_GZ_MODEL_POSE:="0,0,0.95,0,0,0"}

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

# Disable power check for simulation
param set-default CBRK_SUPPLY_CHK 894281

# Control allocation: Quad X
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Rotor positions, using your q940 rotor layout.
# rotor_1: front-right
param set-default CA_ROTOR0_PX 0.25256
param set-default CA_ROTOR0_PY 0.25294
param set-default CA_ROTOR0_KM 0.06

# rotor_2: back-left
param set-default CA_ROTOR1_PX -0.25286
param set-default CA_ROTOR1_PY -0.25265
param set-default CA_ROTOR1_KM 0.06

# rotor_3: front-left
param set-default CA_ROTOR2_PX 0.25268
param set-default CA_ROTOR2_PY -0.25283
param set-default CA_ROTOR2_KM -0.06

# rotor_4: back-right
param set-default CA_ROTOR3_PX -0.25287
param set-default CA_ROTOR3_PY 0.25264
param set-default CA_ROTOR3_KM -0.06

# Gazebo ESC output mapping
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
