float64 s_scale  
float64 x_upper_position 
float64 x_lower_position 
float64 x_upper_velocity
float64 x_lower_velocity
float64 x_upper_accelera
float64 x_lower_accelera
float64 x_0
float64 x_n
float64 x_v0
float64 x_vn
float64 y_upper_position 
float64 y_lower_position 
float64 y_upper_velocity
float64 y_lower_velocity
float64 y_upper_accelera
float64 y_lower_accelera
float64 y_0
float64 y_n
float64 y_v0
float64 y_vn
float64 z_upper_position 
float64 z_lower_position 
float64 z_upper_velocity
float64 z_lower_velocity
float64 z_upper_accelera
float64 z_lower_accelera
float64 z_0
float64 z_n
float64 z_v0
float64 z_vn
---
bool result_status