#!/usr/bin/env bash

DEFAULT_PROFILE="Entity 1"

SITL_PROFILES=(
    "Entity 1| PreGME(季梦玉)模型（laboratory_landingbox）|laboratory_landingbox|gz_q940_ti_gripper4_laboratory_landingbox|-DENABLE_LOCKSTEP_SCHEDULER=ON"
    "Entity 2| PreGME(季梦玉)模型（vla_task0）|laboratory_landingbox_vla_task0|gz_q940_ti_gripper4_laboratory_landingbox_vla_task0|-DENABLE_LOCKSTEP_SCHEDULER=ON"
    "Entity 3| PreGME(公司)模型（laboratory_no_landingbox）|laboratory_no_landingbox|gz_swan_gamma_laboratory_no_landingbox|-DENABLE_LOCKSTEP_SCHEDULER=ON"
    "Entity 4| X500-Gimbal模型(laboratory_no_landingbox) |laboratory_no_landingbox|gz_x500_gimbal_laboratory_no_landingbox|-DENABLE_LOCKSTEP_SCHEDULER=ON"
    "Entity 5| 小车模型 |laboratory_no_landingbox|gz_differential_rover_laboratory_no_landingbox|-DENABLE_LOCKSTEP_SCHEDULER=ON"
)
